server:
  port: 8085

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5556/project_management
    username: postgres
    password: postgres

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:28080/auth/realms/task_manager

      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: admin-cli
            client-secret: Am25Ny6GOHK73SG9Yh9tLBNeICBdLk39
        provider:
          keycloak:
            token-uri: http://localhost:28080/auth/realms/master/protocol/openid-connect/token
