server:
  port: 8085

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5556/project_management
    username: postgres
    password: postgres

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.100:28080/auth/realms/task_manager
